#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 타입 체크
pnpm tsc --noEmit
# 변경된 파일에 대해 린트/포맷
pnpm lint-staged

# 현재 브랜치 확인
if command -v git-branch-is >/dev/null; then
  if git-branch-is main || git-branch-is beta; then
    pnpm run test
  fi
else
  current_branch=$(git rev-parse --abbrev-ref HEAD)
  if [ "$current_branch" = "main" ] || [ "$current_branch" = "beta" ]; then
    pnpm run test
  fi
fi
